"""Added CT model

Revision ID: eeee662837fc
Revises: d30a01ba8870
Create Date: 2024-04-21 23:14:35.543234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeee662837fc'
down_revision: Union[str, None] = 'd30a01ba8870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chick_timer',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('carrier_freq', sa.Float(), nullable=False),
    sa.Column('decoding_success', sa.Boolean(), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('snr_min', sa.Float(), nullable=False),
    sa.Column('snr_max', sa.Float(), nullable=False),
    sa.Column('snr_mean', sa.Float(), nullable=False),
    sa.Column('dbfs_min', sa.Float(), nullable=False),
    sa.Column('dbfs_max', sa.Float(), nullable=False),
    sa.Column('dbfs_mean', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('days_since_change_of_state', sa.Integer(), nullable=True),
    sa.Column('days_since_hatch', sa.Integer(), nullable=True),
    sa.Column('days_since_desertion_alert', sa.Integer(), nullable=True),
    sa.Column('time_of_emergence', sa.Integer(), nullable=True),
    sa.Column('weeks_batt_life_left', sa.Integer(), nullable=True),
    sa.Column('activity_yesterday', sa.Integer(), nullable=True),
    sa.Column('activity_two_days_ago', sa.Integer(), nullable=True),
    sa.Column('mean_activity_last_four_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chick_timer')
    # ### end Alembic commands ###
